name: log_it
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  path: ^1.8.3
  provider: ^6.1.1
  sqflite: ^2.3.2
  camera: ^0.10.5+9
  fl_chart: ^0.66.2
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
