name: build-android
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.16.9'
            cache: true
        - run: flutter pub get
        - run: flutter test
        - run: flutter build apk
        - uses: ncipollo/release-action@v1
          with:
              commit: main
              tag: v${{ github.run_number }}
              artifacts: ./build/app/outputs/flutter-apk/app-release.apk
