name: build-android
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.16.9'
            cache: true
        - run: flutter pub get
        - run: flutter test
        - name: Configure Keystore
          run: |
            echo "$KEY_STORE" | base64 --decode > ./android/upload-keystore.jks
            echo "storeFile=upload-keystore.jks" >> ./android/key.properties
            echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> ./android/key.properties
            echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> ./android/key.properties
          env:
            KEY_STORE: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
            KEYSTORE_KEY_ALIAS: ${{ secrets.ALIAS }}
            KEYSTORE_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        - run: flutter build apk --build-name=${{ github.run_number }}.0.0 --build-number=${{ github.run_number }}
        - run: mv ./build/app/outputs/flutter-apk/app-release.apk ./build/app/outputs/flutter-apk/log-it-${{ github.run_number }}.apk
        - uses: ncipollo/release-action@v1
          with:
              commit: main
              tag: v${{ github.run_number }}
              artifacts: ./build/app/outputs/flutter-apk/log-it-${{ github.run_number }}.apk
      
