name: test
on: [push, workflow_dispatch]
jobs:
  LogIt-Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: flutter test --file-reporter json:reports/tests.json
    - uses: actions/upload-artifact@v3  # upload test results
      if: success() || failure()        # run this step even if previous step failed
      with:
        name: test-results
        path: ./reports/tests.json