name: test
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: flutter test
    - name: Test Report
      uses: phoenix-actions/test-reporting@latest
      id: test-report               # Set ID reference for step
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Dart Tests            # Name of the check run which will be created
        path: reports/test-results.json    # Path to test results
        reporter: flutter-json